### ISSUE TITLE
.Net 7 & 8 SDKs 

### ISSUE THREAD

**Issue by SereetsiKC** [teslahub/docker-teamcity-agent#3]
Hey @thohng, I love to use your repo to create my my own image to add .net 7 and 8 to the agent. how ever I cant use your build actions and your action variables are not visible to us on the settings of your repo. if you don't mind please assist with the values or you may add .net 7 & 8 to your image for us to use. Thank you.

**Comment by thohng** [comment]
Hi @SereetsiKC , thanks for let us know! myself very busy these days. I will look on upgrading .NET this weekend, we also need to upgrade to next .NET SDK also for our usage. Basically, the upgrading quite complex and very detail. You will see the all changes we will make after done. And because we stick to TeamCity v2022.04.4, due to our license. It will be ok for your case because TeamCity Agent can auto upgrade to same version as TeamCity server.

**Comment by SereetsiKC** [comment]
Thank you @thohng , Will keep an eye out next week.

**Comment by thohng** [comment]
Hi SereetsiKC, we just released new 4 builds per 4 TeamCity versions

Version: 2022.04.4, 2022.04.5
```
docker pull teslaconsulting/teamcity-agent:2022.04.4
docker pull teslaconsulting/teamcity-agent:2022.04.5
```

Version: 2022.10.4
```
docker pull teslaconsulting/teamcity-agent:2022.10.4
```

Version: 2023.05.1
```
docker pull teslaconsulting/teamcity-agent:2023.05.1
```

**Comment by SereetsiKC** [comment]
Hey @thohng Thank you for the update and swift attention to my problem.
